amcl:
  ros__parameters:
    use_sim_time: true
    scan_topic: /scan
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0

    laser_model_type: likelihood_field         # ✅ thêm
    odom_model_type: diff                      # ✅ thêm

    # Các tham số bổ sung, nên có
    laser_max_beams: 60
    laser_z_hit: 0.95
    laser_z_short: 0.1
    laser_z_max: 0.05
    laser_z_rand: 0.05
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    update_min_d: 0.25
    update_min_a: 0.2
    max_beams: 60

map_server:
  ros__parameters:
    use_sim_time: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: ""
    plugin_lib_names:
      - nav2/libnav2_compute_path_to_pose_action_bt_node.so
      - nav2/libnav2_follow_path_action_bt_node.so
      - nav2/libnav2_rate_controller_bt_node.so
      - nav2/libnav2_pipeline_sequence_bt_node.so
      - nav2/libnav2_recovery_node_bt_node.so


recoveries_server:
  ros__parameters:
    use_sim_time: true

# recoveries_server:
#   ros__parameters:
#     costmap_topic: local_costmap/costmap_raw
#     footprint_topic: local_costmap/published_footprint
#     cycle_frequency: 10.0
#     recovery_plugins: ["spin", "backup", "wait"]
#     spin:
#       plugin: "nav2_recoveries/Spin"
#     backup:
#       plugin: "nav2_recoveries/BackUp"
#     wait:
#       plugin: "nav2_recoveries/Wait"
